- name: Run using a project directory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: deploy Docker Compose stack
      community.docker.docker_compose_v2:
        project_src: clickhouse-setup
        files:
        - docker-compose-minimal.yaml
        pull: yes
        state: absent
